### ISSUE TITLE
contrastLimits possibly unbound in reader

### ISSUE THREAD

**Issue by tlambert03** [CBI-PITT/napari-imaris-loader#7]
this line here can lead to a possible error `local variable 'contrastLimits' referenced before assignment` depending on the dtype

https://github.com/CBI-PITT/napari-imaris-loader/blob/fccb04f4dafda8e3f16a38150db88faaa5597fc6/napari_imaris_loader/reader.py#L106

**Comment by AlanMWatson** [comment]
Thanks for submitting this issue.  I see how this might happen since the assignment of contrastLimits is not guaranteed.  Do you have a specific example / traceback that caused an issue?  Willing to share the .Ims file?  In any case I will make a note to fix.  Thanks!

**Comment by tlambert03** [comment]
'fraid I don't have the file or a better traceback.  Saw this as a bug that came in through https://github.com/tlambert03/napari-error-reporter ... probably won't be passing these on to plugins forever, but it's still new so I'm doing it for now :)

**Comment by AlanMWatson** [comment]
Understood.  Thanks for passing it along.  I will fix...  Best,
Alan

**Comment by AlanMWatson** [comment]
Issue fixed by ensuring that contrastLimits always receives a value default [0,1]:  v0.1.6
